io:
  save_data_path: ./saves
  asset_path: ./assets
inventory:
  default_capacity: 10
room:
  default_id: 0
resources:
  primary_resource: Health
combat:
  inspection:
    t0: [ABILITIES, INVENTORY, EQUIPMENT, RESOURCES]
    t1: [RESOURCES, EQUIPMENT, ABILITIES]
    t2: [RESOURCES]
