arguments: ["white", "gray", "red", "blue", "green", "orange", "bold", "italic"]
styles:
  item_name : ["blue", "bold"]
  item_desc : ["italic"]
  item_cost : ["red"]
  item_quantity : ["white"]
  currency_gain : ["green", "bold"]
  currency_loss : ["red", "bold"]
  ability_name : ["orange", "bold"]
  ability_desc : ["italic"]
  room_name : ["bold"]
  resource_name: ["orange"]
  resource_value : ["white"]
  resource_max : ["green", "bold"]
  recipe_name : ["white"]
  valid_recipe : ["white"]
  invalid_recipe : ["red"]
  skill_name : ["blue", "bold"]
